POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzQ1ZDA2ZS1hMzIwLTQ3M2EtOTk2Yy0zYjM5NmY4YTY5NDAiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1ODI4MTQ3M30.qQDO63roh7TKfXuguBvbp3laVAeww-DYgXyfYrmW5LY

{
  "title": "Curso de React"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/bb0862e3-f9c5-4646-bc23-7556a4d840db
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzQ1ZDA2ZS1hMzIwLTQ3M2EtOTk2Yy0zYjM5NmY4YTY5NDAiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1ODI4MTQ3M30.qQDO63roh7TKfXuguBvbp3laVAeww-DYgXyfYrmW5LY

###

PUT http://localhost:3333/courses/1
Content-Type: application/json

{
  "title": "Curso de Node.js"
}

###
DELETE http://localhost:3333/courses/7353d99d-34ce-4bb1-b9ea-86ba82eda834


###
POST http://localhost:3333/sessions
Content-Type: application/json  

{
  "email": "PedroHenrique_Pereira@hotmail.com",
  "password": "123456" 
}

###
POST http://localhost:3333/register
Content-Type: application/json  

{
  "name": "Gabriel",
  "email": "praaadin@gmail.com",
  "password": "123456"
}
