POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Cobol"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/7f1ae92e-ada0-48d1-b10b-68d3e46e98be

###

PUT http://localhost:3333/courses/1
Content-Type: application/json

{
  "title": "Curso de Node.js"
}

###
DELETE http://localhost:3333/courses/7353d99d-34ce-4bb1-b9ea-86ba82eda834
